### ISSUE TITLE
and this error

### ISSUE THREAD

**Issue by ghost** [BrianRuizy/b-r.io#52]
![image](https://github.com/BrianRuizy/b-r.io/assets/145942178/a70aaf0b-be6c-49df-b24e-4fdeb13dd39b)

**Comment by BrianRuizy** [comment]
I think these two errors #51 & #52 are related from no blog content coming in. 
Can you share the node version you're using? @mdwebb

**Comment by ghost** [comment]
need same as u said on repo? i used version v18.17.1 how to use v18.3.0?

**Comment by ghost** [comment]
need same as u said on repo? i used version v18.17.1 how to use v18.3.0?

**Comment by ghost** [comment]
How to fix this? i install v18.3.0 based on your repo but i got error again

![image](https://github.com/BrianRuizy/b-r.io/assets/145942178/700b9017-a461-4a51-bf2a-4714d646fea2)

and this my nodejs version based on your readme file
![image](https://github.com/BrianRuizy/b-r.io/assets/145942178/40e037e5-5462-4411-a07a-247f1d15902a)

How to fix it? tags error?

**Comment by BrianRuizy** [comment]
Having a hard time finding the bug, I will get back to you!

**Comment by ghost** [comment]
thanks

**Comment by ghost** [comment]
I solve the problem i change some. 
My NodeJS Version is v18.3.0.

before:
---
title: 'How to create a COVID-19 dashboard with Python'
publishedAt: '2021-09-01'
summary: 'A quick walkthrough overview of the project setup and the technology stack we used.'
tags: ["Big Data", "Python"]
shortTitle: 'Covid Dashboard'
---

after:

---
title: "How to create a COVID-19 dashboard with Python"
publishedAt: "2021-09-01"
summary: "A quick walkthrough overview of the project setup and the technology stack we used."
tags: ["Big Data", "Python"]
shortTitle: Covid Dashboard
---

**Comment by BrianRuizy** [comment]
perfect I see the issue now of mixed use quotes, will be updating code to fix this!
