### ISSUE TITLE
Repository stars not syncing

### ISSUE THREAD

**Issue by tthn0** [BrianRuizy/b-r.io#53]
Discovered an issue where your site is displaying that you have 0 stars on GitHub.
![Screenshot](https://github.com/BrianRuizy/b-r.io/assets/53582981/45c2a70b-38ea-41b4-9f24-fd14170e8ece)

**Comment by BrianRuizy** [comment]
Thanks for the heads up @tthn0. We created the same issue at the same time! 

https://github.com/BrianRuizy/b-r.io/issues/54

This will require changing `api/github/route.ts` to use actual account token. To have increased rate limit.

https://www.endorlabs.com/blog/how-to-get-the-most-out-of-github-api-rate-limits#:~:text=Without%20authorization%2C%20Github%20only%20allows,to%205000%20requests%20per%20hour.

> Without authorization, Github only allows 60 requests per hour (!!), and after creating and using your own personal access token, you are upgraded to 5000 requests per hour.
